### PR TITLE
Add configurable timeouts

### PR DESCRIPTION
**Pull request by mcolyer**
@zachfeldman I found this useful for working with slow WordPress sites. Let me know if there's anything else I need to do to get it integrated.

### CODE REVIEW

**Comment by zachfeldman** [comment]
Hey @mcolyer thanks for the PR! Could you write a test for this? Once you do and tests pass locally, I will merge.

As an FYI, I am removing TravisCI from this repo because I no longer host test sites (too much wordpress spam, hacking, etc because of multi-versioned attack surfaces)

**Comment by mcolyer** [comment]
@zachfeldman I've added a short set of tests in e340be7.

**Comment by zachfeldman** [comment]
@mcolyer if you post a screenshot of all tests passing on your machine, I will merge. Otherwise will need a day or two to get setup again on mine! Sorry, it's been a while :/

**Comment by mcolyer** [comment]
It's probably faster for you to set it up. The tests in that file pass but
I didn't get the integration tests running.
>
>

**Comment by zachfeldman** [comment]
Hey @mcolyer sorry for the delay! Your tests pass for me so I'm going to merge this and deploy a new version of the gem. Thanks!

**Pull request merged**
