### PR TITLE
Fix #38 - Allow tests to run against HTTPS servers

### LINKED ISSUE #38: Tests cannot run against HTTPS hosts
All of the client code supports SSL/HTTPS, but the spec helper does not read enough settings from the environment to allow testing against HTTPS hosts.

Reading from `WORDPRESS_PORT` and `WORDPRESS_USE_SSL` and defaulting to the current literals preserves the current behavior while allowing tests to run against HTTPS servers.

### PR DESCRIPTION
**Pull request by botimer**
This is a simple change to the spec_helper to allow setting a custom
port and whether to use SSL on the underlying XML-RPC client. The README
and sample .env file are updated accordingly.

### CODE REVIEW

**Comment by zachfeldman** [comment]
Thanks for the PR @botimer , just wanted to confirm that tests pass for you locally before merging in?

**Comment by botimer** [comment]
Yes -- all passing, independently and in combination with pull request #40.

**Comment by zachfeldman** [comment]
@botimer https://travis-ci.org/zachfeldman/rubypress/builds/49201835

Build is failing, re-ran it and it failed again - any ideas?

**Comment by botimer** [comment]
Thanks for the super fast response on these -- sorry to give you a headache on a Monday.

I've just remade a minimal (bogus) .env file and the tests are still passing locally. The error according to Travis is:

    $ cd zachfeldman/rubypress
    $ git checkout -qf ed572b51c6dd61ac241b150666ac501d6b854dff
    fatal: reference is not a tree: ed572b51c6dd61ac241b150666ac501d6b854dff
    The command "git checkout -qf ed572b51c6dd61ac241b150666ac501d6b854dff" failed and exited with 128 during .

This appears to have been a problem with Travis builds in the past, but I'm not sure why it would be the case now. It looks like it was most common with really big merges or busy projects (to do with the depth option being too small to include the commit). Maybe this is because the depth on the build is set to 1 and the pull requests were merged in quick sequence? I see ed572b as the second most recent commit, so this seems the most likely issue right now. Maybe just a manual kick-off to retest master?

**Comment by zachfeldman** [comment]
@botimer it was a Travis issue! https://github.com/travis-ci/travis-ci/issues/617

Merged another PR on a whim and it fixed itself. We good! Thanks for your contribution, added you to the README!

**Comment by botimer** [comment]
Great. Thanks for jumping on these, and for the release. Time to take my monkey patch out!

**Pull request merged**
